# Generated by Django 4.0.1 on 2022-02-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
